
import java.awt.*;
import java.io.IOException;
import java.net.URI;

/**
 * HomeFrame.
 *
 * @author Claudio Engeler
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titolo = new javax.swing.JLabel();
        autore = new javax.swing.JLabel();
        fiocco = new javax.swing.JLabel();
        avvia = new javax.swing.JButton();
        sitoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeFrame");
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        titolo.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Fiocchi di neve generator");
        getContentPane().add(titolo);
        titolo.getAccessibleContext().setAccessibleDescription("");

        autore.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        autore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autore.setText("By Claudio Engeler");
        getContentPane().add(autore);

        fiocco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiocco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FioccoDiNeve.png"))); // NOI18N
        getContentPane().add(fiocco);

        avvia.setBackground(new java.awt.Color(255, 255, 255));
        avvia.setFont(new java.awt.Font("Arial Black", 0, 75)); // NOI18N
        avvia.setForeground(new java.awt.Color(0, 255, 255));
        avvia.setText("Avvia");
        avvia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avviaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avviaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avviaMouseExited(evt);
            }
        });
        getContentPane().add(avvia);

        sitoButton.setBackground(new java.awt.Color(255, 255, 255));
        sitoButton.setFont(new java.awt.Font("Arial Black", 0, 75)); // NOI18N
        sitoButton.setForeground(new java.awt.Color(0, 255, 255));
        sitoButton.setText("Help");
        sitoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sitoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sitoButtonMouseExited(evt);
            }
        });
        sitoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sitoButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avviaMouseClicked
        Frame f = new Frame();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_avviaMouseClicked

    private void avviaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avviaMouseEntered
        avvia.setBackground(Color.MAGENTA);
        avvia.setForeground(Color.GREEN);
    }//GEN-LAST:event_avviaMouseEntered

    private void avviaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avviaMouseExited
        avvia.setBackground(Color.WHITE);
        avvia.setForeground(Color.CYAN);
    }//GEN-LAST:event_avviaMouseExited

    private void sitoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitoButtonMouseEntered
        sitoButton.setBackground(Color.MAGENTA);
        sitoButton.setForeground(Color.GREEN);
    }//GEN-LAST:event_sitoButtonMouseEntered

    private void sitoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitoButtonMouseExited
        sitoButton.setBackground(Color.WHITE);
        sitoButton.setForeground(Color.CYAN);
    }//GEN-LAST:event_sitoButtonMouseExited

    private void sitoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitoButtonActionPerformed
        URI url = URI.create("http://samtinfo.ch/i17engcla/SnowFlake/");
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(url);
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_sitoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autore;
    private javax.swing.JButton avvia;
    private javax.swing.JLabel fiocco;
    private javax.swing.JButton sitoButton;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
